name: Build Lambda Package

on:
  push:
    paths:
      - 'lab3_serverless/**'
      - '.github/workflows/build-lambda.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Lambda package using Docker
        run: |
          docker run --rm --entrypoint="/bin/sh" -v "$GITHUB_WORKSPACE/lab3_serverless/lambda_function":/var/task public.ecr.aws/lambda/python:3.9 -c "pip install -r /var/task/requirements.txt -t /var/task/"

      # This step correctly zips the *contents* of the folder
      - name: Upload zip file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lab3_serverless/lambda_function/
